export enum IconName {
  discover = 'discover',
  shortList = 'shortList',
  myAccount = 'myAccount',
  more = 'more',
  news = 'news',
  location = 'location',
  homeLoans = 'homeLoans',
  auction = 'auction',
  estimate = 'estimate',
  findAgents = 'findAgents',
  advice = 'advice',
  viewLogo = 'viewLogo',
  meterSqrt = 'meterSqrt',
  back = 'back',
  filter = 'filter',
  contactUs = 'contactUs',
}
