export enum IconName {
  discover = 'discover',
  shortList = 'shortList',
  myAccount = 'myAccount',
  more = 'more',
  news = 'news',
  location = 'location',
  homeLoans = 'homeLoans',
  auction = 'auction',
  estimate = 'estimate',
  findAgents = 'findAgents',
  advice = 'advice',
  viewLogo = 'viewLogo',
  meterSqrt = 'meterSqrt',
  leftArrow = 'leftArrow',
  rightArrow = 'rightArrow',
  filter = 'filter',
  contactUs = 'contactUs',
  share = 'share',
  bed = 'bed',
  bath = 'bath',
  car = 'car',
  plus = 'plus',
  cross = 'cross',
}
